name: ml_forecasting_project
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.0.9
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - et_xmlfile=1.1.0
  - idna=3.7
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxgboost=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openpyxl=3.1.5
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.0.3
  - pip=24.2
  - platformdirs=3.10.0
  - pooch=1.7.0
  - py-xgboost=2.1.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - urllib3=2.2.3
  - wheel=0.44.0
  - xgboost=2.1.1
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - anyio==4.5.2
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cffi==1.17.1
      - cmdstanpy==1.2.4
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastjsonschema==2.20.0
      - fonttools==4.54.1
      - fqdn==1.5.1
      - h11==0.14.0
      - holidays==0.58
      - httpcore==1.0.6
      - httpx==0.27.2
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.12.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pkgutil-resolve-name==1.3.10
      - plotly==5.24.1
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - prophet==1.1.6
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.4
      - python-json-logger==2.0.7
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - stanio==0.5.1
      - tenacity==9.0.0
      - terminado==0.18.1
      - tinycss2==1.3.0
      - tomli==2.0.2
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - zipp==3.20.2
